/* ==========================================================================
   CHIC CAREER — seed.js
   Loads the DEMO profile, CVs, jobs, applications and past cover letters on
   first run (or when the user asks to reset the demo). "Start fresh" wipes
   everything so the empty states can be explored.
   ========================================================================== */
(function (MT) {
  'use strict';
  const DAY = 86400000;

  function seedDemo() {
    const S = MT.storage;
    S.clearAll();
    const now = Date.now();
    S.set('meta', { schemaVersion: S.SCHEMA_VERSION, seededAt: now, demo: true });
    const d = MT.demo;

    // profile + portfolio
    const profile = JSON.parse(JSON.stringify(d.PROFILE));
    profile.portfolioData = JSON.parse(JSON.stringify(d.PORTFOLIO));
    profile.portfolioUpdatedAt = now - 20 * DAY;
    S.set('profile', profile);

    // CVs (metadata + extracted data only)
    S.set('cvs', d.CVS.map((c) => ({
      id: 'cv_demo_' + MT.ui.hash(c.name).toString(36), name: c.name, filename: c.filename, version: c.version, targetRole: c.targetRole,
      uploadDate: now - c.daysAgo * DAY, size: 182000, sourceType: 'demo', text: c.text, parsedData: c.parsed, isDefault: !!c.isDefault, archived: false
    })));

    // jobs — initial ingest through the real pipeline
    MT.jobsService.refresh({ initial: true });
    const jobs = MT.jobsService.all();
    const jobByKey = (key) => {
      const o = d.OFFERS.find((x) => x.key === key);
      return o ? jobs.find((j) => MT.ui.norm(j.company) === MT.ui.norm(o.company)) : null;
    };
    // keep the "new today" count realistic: older offers were seen before today
    jobs.forEach((j) => { j.firstSeenAt = j.publishedAt; });
    S.set('jobs', jobs);

    // viewed history (a few offers already explored)
    const viewed = {};
    ['brume-social', 'gustave-growth', 'mediaroll-content', 'nordlys-brand', 'pixelune-pmm', 'laitco-acdp', 'hexa-growth', 'opale-maro', 'velvet-events', 'orbe-smm', 'kolibri-seo', 'quanta-data']
      .forEach((k, i) => { const j = jobByKey(k); if (j) viewed[j.id] = now - (i + 2) * DAY; });
    S.set('activity', { viewedJobs: viewed });

    // saved
    const saved = {};
    d.SAVED.forEach((s, i) => { const j = jobByKey(s.jobKey); if (j) saved[j.id] = { savedAt: now - (i + 3) * DAY, notes: s.notes, priority: s.priority }; });
    S.set('saved', saved);

    // applications (+ demo cover letters generated by the real engine, oldest first)
    const cvs = S.get('cvs', []);
    const apps = [];
    S.set('applications', apps);
    d.APPLICATIONS.slice().sort((a, b) => (b.appliedDaysAgo || 0) - (a.appliedDaysAgo || 0)).forEach((a, idx) => {
      const job = a.jobKey ? jobByKey(a.jobKey) : null;
      const snap = job ? { title: job.title, company: job.company, city: job.location, contract: job.contractType, duration: job.duration, source: job.sources[0].source, workMode: job.workMode, industry: job.industry, fields: job.fields, url: job.sources[0].url, salary: job.salary } : a.snapshot;
      const cv = cvs[a.cv] || cvs[0];
      const app = MT.applications.create({
        job, snapshot: snap, status: a.status, cvId: cv.id, notes: a.notes, contact: a.contact, silent: true,
        applicationDate: a.appliedDaysAgo !== undefined ? now - a.appliedDaysAgo * DAY : null
      });
      app.followUpDate = a.followUpIn ? now + a.followUpIn * DAY : (a.appliedDaysAgo !== undefined && ['applied'].indexOf(a.status) !== -1 ? now + 3 * DAY : null);
      app.interviewDate = a.interviewIn ? now + a.interviewIn * DAY + 10 * 3600000 : null;
      app.userAnswers = a.answers || {};
      app.timeline = a.history.map(([type, ago]) => MT.applications.event(type, now - ago * DAY));
      app.createdAt = now - (a.history[0] ? a.history[0][1] : 1) * DAY;
      app.matchScore = job ? MT.matching.score(job, MT.matching.buildKnowledge(cv.id)).score : null;
      if (job && a.history.some((h) => h[0] === 'letter')) {
        try {
          const gen = MT.coverLetter.generate({ job, cvId: cv.id, applicationId: app.id, answers: app.userAnswers, lang: job.language, tone: 'natural', seed: 101 + idx * 37, contactName: (a.contact || {}).name });
          const rec = MT.coverLetter.save(gen, { applicationId: app.id, cvId: cv.id, job });
          const ts = now - (a.appliedDaysAgo || 1) * DAY;
          MT.storage.update('coverLetters', [], (ls) => { const l = ls.find((x) => x.id === rec.id); l.createdAt = ts; l.updatedAt = ts; });
          app.coverLetterId = rec.id; app.coverLetterVersion = 1;
          MT.ai.rememberAnswers(job.company, app.userAnswers);
        } catch (e) { console.warn('demo letter failed', e); }
      }
      app.lastUpdate = now - Math.min(...a.history.map((h) => h[1])) * DAY;
      MT.applications.put(app);
    });

    const reminders = [];
    S.get('applications', []).forEach((a) => {
      if (a.followUpDate) reminders.push({ id: MT.storage.uid('rem'), applicationId: a.id, title: 'Follow up with ' + a.company, date: a.followUpDate, done: false });
      if (a.interviewDate) reminders.push({ id: MT.storage.uid('rem'), applicationId: a.id, title: 'Interview — ' + a.company, date: a.interviewDate, done: false, kind: 'interview' });
    });
    S.set('reminders', reminders);
    S.set('settings', { aiProvider: 'mock', language: 'auto', preferredSources: {} });
    // pretend the last daily refresh happened this morning
    const m = S.get('meta', {});
    const morning = new Date(); morning.setHours(8, 42, 0, 0);
    m.lastRefresh = Math.min(now, morning.getTime());
    S.set('meta', m);
  }

  function startFresh() {
    const S = MT.storage;
    S.clearAll();
    S.set('meta', { schemaVersion: S.SCHEMA_VERSION, seededAt: Date.now(), demo: false });
    S.set('profile', { preferences: { desiredPositions: [], fields: [], industries: [], contracts: ['Stage', 'Alternance'], locations: [], workModes: ['hybrid', 'remote', 'onsite'], durations: [], keywords: [], companies: [] } });
    S.set('settings', { aiProvider: 'mock', language: 'auto' });
    MT.jobsService.refresh({ initial: true });
    const jobs = MT.jobsService.all(); jobs.forEach((j) => { j.firstSeenAt = j.publishedAt; }); S.set('jobs', jobs);
    const m = S.get('meta', {}); m.lastRefresh = Date.now(); S.set('meta', m);
  }

  function ensure() {
    const m = MT.storage.get('meta', null);
    if (!m || m.schemaVersion !== MT.storage.SCHEMA_VERSION) seedDemo();
  }

  MT.seed = { seedDemo, startFresh, ensure };
})(window.MT = window.MT || {});
